#!/bin/bash

# Merges all hashdeep_out.txt files in the subdirectories of the current 
# working directory (one level only, not recursively). The output is  
# printed to stdout and contains a hashdeep-alike header.

# generate a hashdeep-alike header over 5 lines
read -r -d '' header <<- EOM
	%%%% HASHDEEP-1.0 alike style (generated by sync-tools)
	%%%% size,md5,filename
	## Invoked from: ${PWD}
	## Simulates execution of: $ hashdeep -c md5 -v -r -l -W hashdeep_out.txt .
	## 
EOM

# first output the prepared header
echo "$header" 

# loop over subdirectories
for dir in ./*/        # list directories in the form "./dirname/"
do
    # print file content (without header) to stdout
    # prefix the (relative) file paths with the name of the current subdirectory
    hashfile="${dir}hashdeep_out.txt"
    tail -n +6 $hashfile | sed "s@,\.\/@,${dir}@g" 
done

